language: java
jdk:
  - openjdk17
#sudo: false
dist: jammy
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
services:
  - docker
before_install:
  - chmod +x ./publish.sh
  - ls -la /home/travis/.gnupg
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in ./codesigning.asc.enc -out ./codesigning.asc -d
  - gpg2 --batch --import ./codesigning.asc
  - ls -la /home/travis/.gnupg
install: true # disables default "./gradlew assemble"  install script
after_success:
  - ./publish.sh
  - bash <(curl -s https://codecov.io/bash)
script:
 - ./gradlew build codeCoverageReport




